### PR TITLE
parially refactoring to pep 8 and misspell correction

### PR DESCRIPTION
**Pull request by kissarat**
I'll continue if you interesting

### CODE REVIEW

**Comment by xybu** [comment]
Did you do those by hands? If so I am really really sorry... I have abandoned the code base in `1.0-dev`...

And I personally prefer tabs over spaces because it saves me some keystrokes either when indenting or unindenting...

For misspells, I appreciate it if you can point them out so I can check if same mistakes exist in `future` branch.

Sincerely,Xiangyu Bu

Date: Tue, 24 Feb 2015 10:34:42 -0800

**Comment by kissarat** [comment]
Run flake8 and see ) https://pypi.python.org/pypi/flake8
Spaces are the preferred indentation method.
Tabs should be used solely to remain consistent with code that is already indented with tabs.
Python 3 disallows mixing the use of tabs and spaces for indentation.
https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces
"something == None" using instead of "somthing is None"
...
Why do you not use JetBrains PyCharm?

**Comment by xybu** [comment]
Ptr == None is wrong. I agreed. Will fix in "future" branch.

I already used tabs so I guess I am fine with that rule. I don't have mixing of tabs and spaces I think.

Will try out flake8 and fix tabs stuff at some time.

PyCharm is too fat for me. You know what... Ashamed to say it... I use mousepad and sometimes vim...

Sent from my Windows Phone

**Comment by kissarat** [comment]
So you can reject this pull request. I'll refactor future branch and don't replace tabs with spaces

**Comment by xybu** [comment]
Hold on for now. I have local stuff that hasn't been pushed to "future" :)

Sent from my Windows Phone

**Comment by kissarat** [comment]
When will you push your changes?

**Pull request closed without merging**
