### PR TITLE
Fix synchronize with OneDrive and path

### PR DESCRIPTION
**Pull request by snacsnoc**
I've fixed the path (yet again) in `setup.sh` to `cd` to `src` before we execute `skydrive-d`. The reason behind this is that `skydrive-d` calls for `python ./synchronize.py` which does not work when we are not in `src`. As said in the one commit message, this seems like a temporary fix.

`synchronize.py` was also fixed. Before commit 359b785, `synchronize.py` would output `NameError: name 'DirectoryEntry' is not defined` which is the reasoning behind the commit.

### CODE REVIEW

**Comment by xybu** [comment]
The code is still half-baked and I am too busy with my college courses to take care of this project.

Thank you for fixing bugs!

**Comment by xybu** [comment]
How to install the shell skydrive_d along with the python worker to system as a daemon has not been decided yet.

**Comment by snacsnoc** [comment]
No problem. I'll probably be submitting a few pull requests in the future. Namely transitioning references to SkyDrive to OneDrive and some more error checking in `setup.sh`.

**Comment by xybu** [comment]
Thank you!

**Pull request merged**
